version: '3'

services:
  app:
    build: .
    restart: 'no'
    ports:
      - '9000:9000'
    volumes:
      - ./src:/usr/share/nginx/html
    working_dir: /usr/share/nginx/html
  web:
    image: nginx
    depends_on:
      - app
    ports:
      - "8080:80"
    volumes:
      - ./src:/usr/share/nginx/html
      - ./conf/default.conf:/etc/nginx/conf.d/default.conf
  mariadb:
    image: "mariadb"
    depends_on:
      - app
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=123     
      - MYSQL_USER=franklin
      - MYSQL_PASSWORD=123
      - MYSQL_DATABASE=ingresse
